pipeline {
    agent any
    tools {
        go "Go 1.18"
    }
    stages {
//         stage('Checkout') {
//             steps {
//                 git branch: 'master',
//                     credentialsId: 'JeongUn-KIM',
//                     url: 'https://github.com/JeongUn-KIM/jenkins-webhooks-test.git'
//             }
//         }
        stage('Build') {
            steps {
                sh 'pwd'
                sh 'go build jenkinsExample.go'
                sh 'ls'
            }
            post {
                success {
                    echo 'build 성공~'
                }
                failure {
                    echo 'build 실패...'
                }
            }
        }
        stage('Cron Execute') {
            steps {
                    sh './jenkinsExample'
            }
            post {
                success {
                    echo 'main 파일 실행 성공~'
                }
                failure {
                    echo '실패...'
                }
            }
        }
    }
}